import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat, Merriweather } from 'next/font/google'
import localFont from 'next/font/local'
import Footer from '@/components/Footer'

interface IProps {
  children: React.ReactNode
}

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

const merriweather = Merriweather({
  weight: ['400', '700'],
  subsets: ['latin-ext'],
  variable: '--font-merriweather',
})

const monaSans = localFont({
  src: [
    {
      path: '../fonts/Mona-Sans.woff2',
    },
  ],
  variable: '--font-mona-sans',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'jeresc - Front End Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: IProps) {
  return (
    <html
      lang='en'
      className={`${montserrat.variable} ${merriweather.variable} ${monaSans.variable} dark`}
    >
      <body className='bg-white transition-colors duration-700 dark:bg-[#121212]'>
        <Header />
        <main className='mx-auto max-w-7xl p-4'>{children}</main>
        <div className='m-96 min-h-screen' />
        <Footer />
      </body>
    </html>
  )
}
