import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Merriweather } from "next/font/google";
import localFont from "next/font/local";

const montserrat = Montserrat({
  subsets: ["latin"],
});

const merriweather = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const monaSans = localFont({
  src: [
    {
      path: "../fonts/Mona-Sans.woff2",
    },
  ],
});

export const metadata: Metadata = {
  title: "jeresc - Front End Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          monaSans.className +
          " " +
          merriweather.className +
          " " +
          montserrat.className +
          " dark bg-white dark:bg-[#121212]"
        }
      >
        <Header />
        <main className="max-w-5xl mx-auto p-4 ">{children}</main>
      </body>
    </html>
  );
}
