import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Merriweather } from 'next/font/google'
import localFont from 'next/font/local'

const montserrat = Montserrat({
  subsets: ['latin'],
})

const merriweather = Merriweather({
  weight: ['400', '700'],
  subsets: ['latin-ext'],
})

const monaSans = localFont({
  src: [
    {
      path: '../fonts/Mona-Sans.woff2',
    },
  ],
  variable: '--font-mona-sans',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'jeresc - Front End Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={
          monaSans.className +
          ' ' +
          merriweather.className +
          ' ' +
          montserrat.className +
          ' bg-white dark:bg-[#121212]'
        }
      >
        <Header />
        <main className='mx-auto p-4 '>{children}</main>
        <div className='mt-96 min-h-screen'></div>
      </body>
    </html>
  )
}
